### Is PCA even needed?

In [2]:
import numpy as np
import pandas as pd
import sklearn


In [3]:
from sklearn.datasets import load_wine
Data = load_wine()

In [8]:
X = Data.data
y = Data.target

In [9]:
D = pd.DataFrame(X)
p = pd.DataFrame(y)

In [10]:
D.head()

0     1     2     3      4     5     6     7     8     9    10    11  \
0  14.23  1.71  2.43  15.6  127.0  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  13.20  1.78  2.14  11.2  100.0  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2  13.16  2.36  2.67  18.6  101.0  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3  14.37  1.95  2.50  16.8  113.0  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4  13.24  2.59  2.87  21.0  118.0  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

       12  
0  1065.0  
1  1050.0  
2  1185.0  
3  1480.0  
4   735.0

In [11]:
D.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
dtype: int64

In [12]:
Data1 = D.rename(columns = {0:'Alcohol', 1:'Malic_Acid', 2:'Ash', 3:'Alcalinity_of_Ash', 4:'Magnesium', 5:'Total_phenol', 6:'Flavonoid', 7:'Nonflavonoid', 8:'Proanthocynins', 9:'Color_intensity', 10:'Hue', 11:'Diluted_wines', 12:'Proline'})
Data1.head()

Alcohol  Malic_Acid   Ash  Alcalinity_of_Ash  Magnesium  Total_phenol  \
0    14.23        1.71  2.43               15.6      127.0          2.80   
1    13.20        1.78  2.14               11.2      100.0          2.65   
2    13.16        2.36  2.67               18.6      101.0          2.80   
3    14.37        1.95  2.50               16.8      113.0          3.85   
4    13.24        2.59  2.87               21.0      118.0          2.80   

   Flavonoid  Nonflavonoid  Proanthocynins  Color_intensity   Hue  \
0       3.06          0.28            2.29             5.64  1.04   
1       2.76          0.26            1.28             4.38  1.05   
2       3.24          0.30            2.81             5.68  1.03   
3       3.49          0.24            2.18             7.80  0.86   
4       2.69          0.39            1.82             4.32  1.04   

   Diluted_wines  Proline  
0           3.92   1065.0  
1           3.40   1050.0  
2           3.17   1185.0  
3           3.45   1480.0  
4           2.93    735.0

In [22]:
from sklearn.decomposition import PCA 
  
pca = PCA(n_components = 5) 
pc = PCA(n_components = 8)
x = pc.fit_transform(Data1)
X = pca.fit_transform(Data1)  
  
explained_variance = pca.explained_variance_ratio_
explained_variance1 = pc.explained_variance_ratio_

In [23]:
#n_components is the numbers of features chosen from the set of features(in descending order of most importance)
explained_variance

array([9.98091230e-01, 1.73591562e-03, 9.49589576e-05, 5.02173562e-05,
       1.23636847e-05])

In [24]:
explained_variance1

array([9.98091230e-01, 1.73591562e-03, 9.49589576e-05, 5.02173562e-05,
       1.23636847e-05, 8.46213034e-06, 2.80681456e-06, 1.52308053e-06])

In [25]:
comp = pc.components_
comp

array([[ 1.65926472e-03, -6.81015556e-04,  1.94905742e-04,
        -4.67130058e-03,  1.78680075e-02,  9.89829680e-04,
         1.56728830e-03, -1.23086662e-04,  6.00607792e-04,
         2.32714319e-03,  1.71380037e-04,  7.04931645e-04,
         9.99822937e-01],
       [ 1.20340617e-03,  2.15498184e-03,  4.59369254e-03,
         2.64503930e-02,  9.99344186e-01,  8.77962152e-04,
        -5.18507284e-05, -1.35447892e-03,  5.00440040e-03,
         1.51003530e-02, -7.62673115e-04, -3.49536431e-03,
        -1.77738095e-02],
       [-1.68738094e-02, -1.22003373e-01, -5.19874304e-02,
        -9.38593003e-01,  2.97802484e-02,  4.04846439e-02,
         8.54433387e-02, -1.35107797e-02,  2.46593824e-02,
        -2.91398464e-01,  2.59776624e-02,  7.03239693e-02,
        -4.52868159e-03],
       [-1.41446778e-01, -1.60389543e-01,  9.77280992e-03,
         3.30965260e-01,  5.39375605e-03,  7.45846556e-02,
         1.69086724e-01, -1.08055610e-02,  5.01209524e-02,
        -8.78893693e-01,  6.00349446e

In [30]:
pcaa = PCA(n_components = 0.5,svd_solver = 'full')
XX = pcaa.fit_transform(Data1)
ex = pcaa.explained_variance_ratio_

In [31]:
ex

array([0.99809123])

In [32]:
#Till now i have three types of data with different dimensions, lets see which one provides best accuracy.

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

X_train1, X_test1, y_train1, y_test1 = train_test_split(x, y, test_size = 0.3, random_state = 0)

X_train2, X_test2, y_train2, y_test2 = train_test_split(XX, y, test_size = 0.3, random_state = 0)

In [34]:
# Fitting the classifier to the Training set
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=200, criterion='entropy', random_state = 1)
model.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=200, random_state=1)

In [35]:
y_pred = model.predict(X_test)
model.score(X_test, y_test)


0.9629629629629629

In [36]:
model.fit(X_train1, y_train1)
y_pred = model.predict(X_test1)
model.score(X_test1, y_test1)

0.9814814814814815

In [37]:
model.fit(X_train2, y_train2)
y_pred = model.predict(X_test2)
model.score(X_test2, y_test2)

0.6851851851851852

In [41]:
Model = RandomForestClassifier(n_estimators = 50, criterion = 'gini', random_state = 0)
Model.fit(X_train1, y_train1)
pred = Model.predict(X_test1)
Model.score(X_test1, y_test1)

0.9814814814814815

In [43]:
Model.base_estimator_

DecisionTreeClassifier()

In [44]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler() 
  
pp = sc.fit_transform(Data1) 
ppp = sc.fit_transform(x)

In [45]:
#pp is basic data with doing any dimensionality reduction and the other is with.

X_train3, X_test3, y_train3, y_test3 = train_test_split(pp, y, test_size = 0.3, random_state = 0)

X_train4, X_test4, y_train4, y_test4 = train_test_split(ppp, y, test_size = 0.3, random_state = 0)

MOdel = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 0)
MOdel.fit(X_train3, y_train3)
pred = MOdel.predict(X_test3)
MOdel.score(X_test3, y_test3)

0.9814814814814815

In [46]:
MOdel.fit(X_train4, y_train4)
pred = MOdel.predict(X_test4)
MOdel.score(X_test4, y_test4)

0.9629629629629629

In [ ]:
#So no fucking change if i use StandarScaler on pca-ed data.
#Either im doing something wrong or the data is too small for the changes to occur